Blog.WebUI.Site/Controllers/CategoryController.cs
namespace Blog.WebUI.Site.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Blog.Data;
    using Blog.WebUI.Site.Models;

    public class CategoryController : Controller
    {
        CategoryData _categoryData;
        ContentData _contentData;
        ContentCategoryData _contentCategoryData;

        public CategoryController(CategoryData _categoryData, ContentData _contentData, ContentCategoryData _contentCategoryData)
        {
            this._categoryData = _categoryData;
            this._contentData = _contentData;
            this._contentCategoryData = _contentCategoryData;
        }

        public IActionResult Index(string slug, int page = 1)
        {
            var category = _categoryData.GetBy(x => x.Slug == slug && x.IsActive && !x.IsDeleted).FirstOrDefault();
            if (category == null)
                return RedirectToAction("Index", "Home", new { q = "kategori-bulunamadi" });

            var category_content_ids = _contentCategoryData.GetByPage(x => x.CategoryId == category.Id, page, 10)
                .Select(x => x.ContentId).ToList();
            var total_data = _contentCategoryData.GetCount(x => x.CategoryId == category.Id);
            double c = double.Parse(total_data.ToString()) / 10;
            c = Math.Ceiling(c);

            var contents = _contentData.GetContentsByIds(category_content_ids, 10);

            var model = new CategoryViewModel()
            {
                Category = category,
                Contents = contents,
                CurrentPage = page,
                TotalData = total_data,
                TotalPage = c,
            };

            return View(model);
        }
    }
}

Blog.WebUI.Site/Controllers/TagController.cs
namespace Blog.WebUI.Site.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Blog.Data;
    using Blog.WebUI.Site.Models;

    public class TagController : Controller
    {
        TagData _tagData;
        ContentData _contentData;
        ContentTagData _contentTagData;

        public TagController(TagData _tagData, ContentData _contentData, ContentTagData _contentTagData)
        {
            this._tagData = _tagData;
            this._contentData = _contentData;
            this._contentTagData = _contentTagData;
        }

        public IActionResult Index(string slug, int page = 1)
        {
            var tag = _tagData.GetBy(x => x.Slug == slug && x.IsActive && !x.IsDeleted).FirstOrDefault();
            if (tag == null)
                return RedirectToAction("Index", "Home", new { q = "etiket-bulunamadi" });

            var category_content_ids = _contentTagData.GetByPage(x => x.TagId == tag.Id, page, 10)
                .Select(x => x.ContentId).ToList();
            var total_data = _contentTagData.GetCount(x => x.TagId == tag.Id);
            double c = double.Parse(total_data.ToString()) / 10;
            c = Math.Ceiling(c);

            var contents = _contentData.GetContentsByIds(category_content_ids, 10);

            var model = new TagViewModel()
            {
                Tag = tag,
                Contents = contents,
                CurrentPage = page,
                TotalData = total_data,
                TotalPage = c,
            };

            return View(model);
        }
    }
}

Blog.WebUI.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr" class="no-js">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title</title>
    <link href="~/_assets/css/media_query.css" rel="stylesheet" type="text/css" />
    <link href="~/_assets/css/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="~/_assets/css/animate.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    <link href="~/_assets/css/owl.carousel.css" rel="stylesheet" type="text/css" />
    <link href="~/_assets/css/owl.theme.default.css" rel="stylesheet" type="text/css" />
    <link href="~/_assets/css/style_1.css" rel="stylesheet" type="text/css" />
    <script src="~/_assets/js/modernizr-3.5.0.min.js"></script>

    @RenderSection("styles", false)

</head>
<body>
    <div class="container-fluid">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-3 fh5co_padding_menu">
                    <img src="~/_assets/images/logo.png" alt="img" class="fh5co_logo_width" />
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid bg-faded fh5co_padd_mediya padding_786">
        <div class="container padding_786">
            <nav class="navbar navbar-toggleable-md navbar-light ">
                <button class="navbar-toggler navbar-toggler-right mt-3" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="fa fa-bars"></span>
                </button>
                <a class="navbar-brand" href="#"><img src="~/_assets/images/logo.png" alt="img" class="mobile_logo_width" /></a>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">

                        <li class="nav-item active">
                            <a class="nav-link" href="@Url.Action("Index","Home")">Ana Sayfa <span class="sr-only">(current)</span></a>
                        </li>
                        @foreach(var item in cache.Categories)
                        {
                            <li class="nav-item ">
                                <a class="nav-link" href="@Url.Action("Index","Category", new { slug = item.Slug })">@item.Name <span class="sr-only">(current)</span></a>
                            </li>
                        }

                    
                       
                        <li class="nav-item dropdown">
                           
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink_1">
                              
                            </div>
                        </li>
                  
                        <li class="nav-item ">
                           
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>

    @RenderBody()

    <div class="container-fluid fh5co_footer_bg pb-3">
        <div class="container animate-box">
            <div class="row">
                <div class="col-12 spdp_right py-5"><img src="~/_assets/images/white_logo.png" alt="img" class="footer_logo" /></div>
                <div class="clearfix"></div>
                
            </div>
            
        </div>
    </div>

    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="fa fa-arrow-up"></i></a>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="~/_assets/js/owl.carousel.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
            integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
            integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
            crossorigin="anonymous"></script>
    <script src="~/_assets/js/jquery.waypoints.min.js"></script>
    <script src="~/_assets/js/main.js"></script>

</body>
</html>

Blog.WebUI.Site/Views/Shared/_SideBar.cshtml
<div class="col-md-3 animate-box" data-animate-effect="fadeInRight">
    <div>
        <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">Tags</div>
    </div>
    <div class="clearfix"></div>
    <div class="fh5co_tags_all">

        @foreach (var item in cache.GetTags)
       {
           <a href="@Url.Action("Index", "Tag", new { slug = item.Slug })" class="fh5co_tagg">@item.Name</a>
       }

    </div>
</div>